# Generated by Django 4.0.5 on 2022-06-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('coding', 'coding'), ('sports', 'sports'), ('technology', 'technology')], max_length=30),
        ),
    ]
